### ISSUE TITLE
XCode 7 and ATS

### ISSUE THREAD

**Issue by NitroG42** [einsteinx2/iSub#12]
Hello, I tried to build the project on iOS9 (iPad Air 2) with XCode 7, but the app crash at start (saying it requires a view controller at the end of the splash but the delegate definitelly set one).

I'm not sure but I think it might be related to ATS ? http://stackoverflow.com/questions/30739473/nsurlsession-nsurlconnection-http-load-failed-on-ios-9
Because in the logs it said it can't make some http request.
Also, it tries to create a (null).db in the DatabaseCode. The error comes from the metadata db, it uses SettingsS.uuid but it is nil at time of creation... I'm not sure why there are all thoses crashes.
Thank you for your help.

**Comment by addisflava** [comment]
Hi  there I had a similar issue with another app , but i could not get isub to compile . I  get a lot of missing files , i try my best to find those files like  libsub & ex2kit but get more missing files .Could you please share how you did it . the ATS problem is from ios preventing plain http for authenthication . Since subsonic api currently only supports http (I think Masonic new api use https ) . There are ways you can disable it in xcode search on googel i used this here http://iosdevtips.co/post/121756573323/ios-9-xcode-7-http-connect-server-error

**Comment by einsteinx2** [comment]
Hey guys thanks for the reports. The crash was due to me setting the main window to a new object (old iOS 7 display hack). And the other issue just required an extra entry in the Info plist to allow insecure connections. 

Both are now fixed in the master branch.
