### ISSUE TITLE
Issues, ideas and feature requests

### ISSUE THREAD

**Issue by kibzwolf** [einsteinx2/iSub#16]
Hey guys,

So I'm just gonna list issues and ideas/feature requests here. I know not to expect anything it's just here for you to see. 
- When I search a song and play it, it adds other songs with similar titles to a playlist and plays them all. (Would be good if it just played that one song instead?) 
- I noticed most streaming apps don't allow the seek bar to slide through the track from locked screen or slid up from bottom of screen? Have to go into the app to seek?
- Love the info showing for each track (bit rate, year, genre, track, etc. hope that stays.)
- 25 (or whatever) most played songs playlist. (Not sure if that's possible but I used this feature very often on iOS music app. 
- Moving tracks up and down in queue/playlist by holding and dragging rather than having to tap edit to move it? 
- Love the app icon but maybe the old aqua/cyan color looks better on black? Not a big deal though. 
- Love how the seeking works when it fades out and back into the song when you have stopped seeking. Hoping that stays. Along with the download progress of the song over the seek bar. Really cool. 
- When selected to cache only beginning of the song it corrupts the song from the point it stops caching (hard to explain. It skips if you use that option). Using that option was a no go because of that. 
- Shuffling a folder (big collection) takes a few minutes to start playing and then a few more minutes it will continue to add songs to the queue/current playlist. 
- Give option to view all songs/files (folder view + all music view for easy shuffle)
- Downloading resets often on cellular (when I download a song/folder). Works fine on WIFI but usually it will download half or almost all of the song and then reset and start over. 
- resume download: when a song downloads and you change the song before it finishes downloading it will start downloading again from the beginning when you go back to it.

**Comment by luckydonald** [comment]
- when playing a song there is no quick way to set the stars or favorite it.

**Comment by einsteinx2** [comment]
Sorry I've waited forever to respond to this! Now that I'm getting all the issues organized, I'll reply item by item and create issues as needed:

- When I search a song and play it, it adds other songs with similar titles to a playlist and plays them all. (Would be good if it just played that one song instead?) 

Yep this should either just queue the song next or load only the song you tapped or something better than it does now.

- I noticed most streaming apps don't allow the seek bar to slide through the track from locked screen or slid up from bottom of screen? Have to go into the app to seek?

To my knowledge, prior to iOS 11, no audio apps other than the Music app could allow seeking from the lock screen. In iOS 11 I've seem Spotify do it, but haven't found the API in the documentation yet. Assuming they didn't get special access, I will add support for this.

- Love the info showing for each track (bit rate, year, genre, track, etc. hope that stays.)

Definitely staying. The player will allow toggling between regular mode (all info, smaller controls) to running/car mode (less info, larger controls and song name). A proof of concept version of this has already been implemented.

- 25 (or whatever) most played songs playlist. (Not sure if that's possible but I used this feature very often on iOS music app. 

Looks like Subsonic still only has a top albums API call, unless I missed something in the docs. So this wouldn't be possible, but top albums would be.

- Moving tracks up and down in queue/playlist by holding and dragging rather than having to tap edit to move it? 

This is exactly how it works :)
Also dragging songs into the play queue works.

- Love the app icon but maybe the old aqua/cyan color looks better on black? Not a big deal though.

iSub 4 will have a brand new icon to go with the new UI skinning
 
- Love how the seeking works when it fades out and back into the song when you have stopped seeking. Hoping that stays. Along with the download progress of the song over the seek bar. Really cool. 

I figured out how to reduce the seek time to 0 (I was fading before to hide the delay), however I do like the fade and it has stayed albeit with a shorter time. 

When the player UI is finished there will definitely be some way of seeing the download progress, probably exactly like iSub 3.

- When selected to cache only beginning of the song it corrupts the song from the point it stops caching (hard to explain. It skips if you use that option). Using that option was a no go because of that. 

Unfortunately that was something that used to work on older iOS and Subsonic versions but doesn't anymore for technical reasons. The option has been removed.

- Shuffling a folder (big collection) takes a few minutes to start playing and then a few more minutes it will continue to add songs to the queue/current playlist. 

This will be improved.

- Give option to view all songs/files (folder view + all music view for easy shuffle)

Subsonic has a server shuffle API call that I use, and will be increasing the number of songs from 100 to something larger (or will load new ones as needed). An all songs view isn't really possible unfortunately. iSub used to do it with a bit of a hack, but it was never reliable.

- Downloading resets often on cellular (when I download a song/folder). Works fine on WIFI but usually it will download half or almost all of the song and then reset and start over. 

Not sure what's going on there, but the whole cache system has been rewritten.

- resume download: when a song downloads and you change the song before it finishes downloading it will start downloading again from the beginning when you go back to it. 

If you mean auto-caching while listening, this is by design as if you skip past the song you may not have bandwidth to download both at once or even want the previous song.


@luckydonald definitely want to add support for this, but I've moved it to after iSub 4 as there is a feature freeze to ensure it gets released.
