### ISSUE TITLE
Ios10 breaks folder refresh

### ISSUE THREAD

**Issue by p-ang** [einsteinx2/iSub#47]
I suspect that it is a UI issue. When a folder has very few items, it is not possible to scroll up and therefore invoke the folder refresh command.

**Comment by einsteinx2** [comment]
Good catch! I guess I just never tried to refresh a small folder, and didn't get any reports about it. I'll fix it, thanks.

**Comment by p-ang** [comment]
Thanks :-)


On 20 Sep 2016, at 02:29, Ben Baron <notifications@github.com<mailto:notifications@github.com>> wrote:


Good catch! I guess I just never tried to refresh a small folder, and didn't get any reports about it. I'll fix it, thanks.

-

**Comment by DanielKaparunakis** [comment]
I second this issue. If you tap on the search bar, it'll then let you refresh though.

**Comment by einsteinx2** [comment]
Man it's fun trying to get an old branch to build after a long time working on a different branch...FML

**Comment by DanielKaparunakis** [comment]
Off topic, are you interested at all in keeping this project alive? Because to this day, I use your app 20+ hours per week and it just works.

**Comment by einsteinx2** [comment]
@p-ang @DanielKaparunakis Super late reply, but I finally did get the old branch building, it's now in a new repo at http://github.com/einsteinx2/iSub3. I'll be keeping it up to date now that I can actually build it.

@DanielKaparunakis To answer your question, take a look at all the commits since you posted :)
